version: '3.3'
services:
  JPA:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '2222:3306'
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '3333:8080'

volumes:
  my-db: